#!/bin/csh -f

set file1 = $1
set file2 = $2

set n = `cat $file1 | wc -l`

@ i = 1

while ($i <= $n)
  set line1 = `sed -n "$i{p;q}" $file1`
  set line2 = `sed -n "$i{p;q}" $file2`

  echo "$line1 $line2"

  @ i = $i + 1
end

exit 0
