#!/bin/csh -f

if      ($#argv == 2) then
  set src = $1
  set dst = $2
else if ($#argv == 1) then
  set src = $1
  set dst = `pwd`
else
  echo "Usage: link_missing <src> [<dst>]"
  exit 1
endif

cd $src

foreach f (*)
  cd $dst

  if (! -e $f) then
    ln -s $src/$f .
  endif
end

exit 0
