#!/bin/csh -f

#valgrind --suppressions=/home/colinw/.suppressions --leak-check=full --leak-resolution=high --show-leak-kinds=all --log-file=valgrind.log $*

valgrind --demangle=yes --suppressions=/home/colinw/.suppressions --gen-suppressions=all --leak-check=full --show-reachable=yes --error-limit=no --leak-resolution=high --show-leak-kinds=all --log-file=valgrind.log $*

exit 0
