#!/bin/csh -f

set files = ()
set link  = 1
set view  = 0

while ($#argv > 0)
  if      ("$1" == "-L") then
    set link = 0
    shift
  else if ("$1" == "-v") then
    set view = 1
    shift
  else
    set files = ($files $1)
    shift
  endif
end

if ($#files == 0) then
  echo "No files"
  exit 1
endif

if ($link == 1) then
  CConcat $files > .all
else
  CConcat -L $files > .all
endif

if ($view == 1) then
  view .all
else
  vi .all
endif

CUnconcat .all

#rm .all

exit 0
