#!/bin/csh -f

if ($#argv != 2) then
  echo "Usage $argv[0] <old_name> <new_name>"
  exit 1
endif

set old_name = $argv[1]
set new_name = $argv[2]

set lower_old = `echo $old_name | tr "[A-Z]" "[a-z]"`
set upper_old = `echo $old_name | tr "[a-z]" "[A-Z]"`
set caps_old  = `echo "${upper_old}:${lower_old}" | sed 's/\(.\).*:./\1/'`

set lower_new = `echo $new_name | tr "[A-Z]" "[a-z]"`
set upper_new = `echo $new_name | tr "[a-z]" "[A-Z]"`
set caps_new  = `echo "${upper_new}:${lower_new}" | sed 's/\(.\).*:./\1/'`

echo ':1,$s'"/$lower_old/$lower_new/g"
echo ':1,$s'"/$upper_old/$upper_new/g"
echo ':1,$s'"/$caps_old/$caps_new/g"

exit 0
